### ISSUE TITLE
Compatibility with Magento >=2.4.7

### ISSUE THREAD

**Issue by simonmaass** [netresearch/module-shipping-inventory#3]
I get the following error when installing with magento 2.4.7:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - netresearch/module-shipping-inventory[1.0.0, ..., 1.0.1] require php ^7.1.3 -> your php version (8.2.14) does not satisfy that requirement.
    - netresearch/module-shipping-inventory[1.1.0, ..., 1.1.2] require netresearch/module-shipping-core ^2.8.0 -> found netresearch/module-shipping-core[2.8.0, 2.8.1, 2.8.2, 2.9.0] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires netresearch/module-shipping-inventory * -> satisfiable by netresearch/module-shipping-inventory[1.0.0, ..., 1.1.2].

**Comment by Sebastian80** [comment]
Hi @simonmaass,

we released a new [version](https://github.com/netresearch/module-shipping-inventory/releases/tag/1.2.0) which includes the [changes](https://github.com/netresearch/module-shipping-inventory/commit/482fedeaa25b00fda66a51e979fe53f564ab8ac9) from your [PR](https://github.com/netresearch/module-shipping-inventory/pull/4).
